name: SSH into EC2

on:
  push:
    branches:
      - main

jobs:
  ssh-into-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2
        run: |
          sudo ssh -i "461Key.pem" ec2-user@ec2-18-227-26-233.us-east-2.compute.amazonaws.com
