name: Simple Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo ${{ secrets.EC2_SSH_KEY }} | base64 -d > ~/.ssh/ec2_ssh_key
          chmod 600 ~/.ssh/ec2_ssh_key
          ssh-keyscan 18.227.26.233 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy code to EC2
        run: |
          ssh -i ~/.ssh/ec2_ssh_key ec2-user@18.227.26.233 "cd ./ && git pull && npm install && tsc"
