name: SSH into EC2 Instance and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH into EC2 and Deploy
      run: |
        mkdir -p $HOME/.ssh
        touch $HOME/.ssh/known_hosts
        sudo ssh -o StrictHostKeyChecking=no -i ./461Key.pem 
        ec2-user@18.227.26.233 "cd ./ECE461_Phase2 && git pull 
        && npm install"
