name: SSH into EC2 and Setup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/ec2_ssh_key
          chmod 600 ~/.ssh/ec2_ssh_key
          ssh-keyscan YOUR_EC2_PUBLIC_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH into EC2 and Run Commands
        run: |
          ssh -i ~/.ssh/ec2_ssh_key ec2-user@YOUR_EC2_PUBLIC_IP "cd /path/to/your/project && git pull && npm install && tsc"
