name: Write Secret to File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 Instance
        run: |
          sudo ssh -i "461Key.pem" ec2-user@18.227.26.233.us-east-2.compute.amazonaws.com

