name: Write Secret to File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create and Write Secret to File
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > secret.txt
      env:
        YOUR_SECRET_NAME: ${{ secrets.EC2_SSH_KEY }}

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add secret.txt
        git commit -m "Add secret.txt"
        git push

