name: SSH into EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH into EC2 Instance
      run: |
        ssh -i "461Key.pem" ec2-user@18.227.26.233.us-east-2.compute.amazonaws.com
